#!/bin/bash

sudo ln -n ./phpStettings/my_php_settings.ini /etc/php/7.2/apache2/conf.d/my_php_settings.ini
sudo ln -n ./phpStettings/my_php_settings.ini /etc/php/7.4/apache2/conf.d/my_php_settings.ini
sudo ln -n ./phpStettings/my_php_settings.ini /etc/php/8.0/apache2/conf.d/my_php_settings.ini
sudo ln -n ./phpStettings/my_php_settings.ini /etc/php/8.1/apache2/conf.d/my_php_settings.ini
sudo ln -n ./phpStettings/my_php_settings.ini /etc/php/8.2/apache2/conf.d/my_php_settings.ini

sudo systemctl restart apache2 
